### ISSUE TITLE
Cancel button doesn't close Add Skills form

### ISSUE THREAD

**Issue by smokinGun** [maryvilledev/skilldirectoryui#103]
When clicking Cancel button on Add Skills form there is no response.

**Comment by solkaz** [comment]
@jdmaryville what I have noticed is that the callback function prop is not being passed into the `AddSkillForm` from `Skills`. So you just have to pass the function into the prop in `Skills`

**Comment by solkaz** [comment]
Closed as I fixed this in [this PR](https://github.com/maryvilledev/skilldirectoryui/pull/111)

**Comment by solkaz** [comment]
foobarbaz
