### ISSUE TITLE
Add Cancel Buttons to all forms

### ISSUE THREAD

**Issue by smokinGun** [maryvilledev/skilldirectoryui#105]

**Comment by solkaz** [comment]
May I say that this might signal the fact that it might be good to make a generic `Form` component. Between the many forms we have in SkillDirectory, most if not all have common characteristics such as:
- A "do action" button (delete, add new item, etc)
- A cancel button
- A title
- Forms to fill out, or text to display. 

I think we would benefit from abstracting a general form that would be used to compose the necessary forms. Thoughts @thebho ?

**Comment by thebho** [comment]
I concur with that statement
