### ISSUE TITLE
Skill Reviews that are longer than 2 lines have a wrapping problem on the skill page

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#110]
Adding photo as an example.  The Text should all be inline.

**Comment by thebho** [comment]
<img width="1207" alt="screen shot 2017-01-25 at 8 41 38 am" src="https://cloud.githubusercontent.com/assets/12362348/22294819/53e521aa-e2da-11e6-8484-7738227dc500.png">

**Comment by dane-johnson** [comment]
If I were to guess why, I would think that maybe the Col it is in has a floor that the text is exceeding.

**Comment by thebho** [comment]
This was fixed with the re-design
