### ISSUE TITLE
Display link_type as icon

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#142]
Instead of `Webpage: Java Home`, it should be:
`{icon} Java Home`

**Comment by thebho** [comment]
I like these options: https://material.io/icons/

Suggestions:
Home (for Webpage/Home page)
Library Books (for Tutorial)
Computer (for Blog)

**Comment by Hopding** [comment]
I like the idea of adding icons, but I do not think that we should remove the text too. I don't think the icons are clear enough to somebody who does not already know what they  mean (everybody not on the co-op team). So, I would suggest `{icon} Webpage: Java Home`

**Comment by thebho** [comment]
How about hover displays the type?

**Comment by Hopding** [comment]
Hovering for the type might work.

In addition to adding icons, it may also be useful to separate them into sections. So instead of:
```
Webpage: xxx
Webpage: xxx
Webpage: xxx
Blog: xxx
Blog: xxx
Blog: xxx
...
```
... we should have
```
Webpage:
   xxx
   xxx
   xxx
Blog:
   xxx
   xxx
   xxx
...
```

**Comment by thebho** [comment]
Yeah, that's a good option.  I'd be curious how they each look mocked up
