### ISSUE TITLE
Add PropType checking to components

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#26]
None of the components in this project leverage PropType checking, which could be used to help us debug the components during development by checking the type of the prop passed to a component. It only takes a few minutes to add them to a component, and they can only help us, as there are no performance penalties in production code (because PropType checking is disabled in prod environments)

**Comment by thebho** [comment]
Sounds good.  Adding to Ready

**Comment by solkaz** [comment]
I will say that right now, there's only one place where we are passing props (Skill -> SkillForm). I think that as we're developing components, we should make sure to define the PropTypes so that we're getting typechecking

**Comment by Hopding** [comment]
It looks to me like all of the components that use `props` have prop type checking for them already. Was this story placed back in ready status by mistake?
