### ISSUE TITLE
Design a confirm delete generic component

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#32]
The modal should look like this: http://www.jqueryscript.net/images/Delete-Confirmation-Dialog-Plugin-with-jQuery-Bootstrap.jpg

And be easily reused in other components

Refactor the Delete skills to use this component

**Comment by dane-johnson** [comment]
I could probably just rename the DeleteSkillModal and change it's appearance a bit and I think it would work just fine.

**Comment by solkaz** [comment]
I've made a component that does this in [this PR](https://github.com/maryvilledev/skilldirectoryui/pull/42). It just take a few minutes to refactor the Skill and Team components to use it.
