### ISSUE TITLE
Adding a linter to the project

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#34]
The project is expanding to include three more members (myself included), all of whom with different experience in Javascript. I propose adding a linter to the project to set a standard style for the project, to enforce readability and to help catch silly errors (like misspelling a variable) more quickly.

I have used [eslint](http://eslint.org/) before and can attest to its great support for React projects and the low number of false positives (sometimes will flag valid ES7), as well as enforcing indentation, single vs. double quotes for strings, and requiring the use of a semicolon. It also supports Jest (which we use for testing) and ES6

**Comment by solkaz** [comment]
@thebho what style do we want to use? There are a number of guides; one that is highly regarded is [Airbnb's style guide](https://github.com/airbnb/javascript), which concerns Javascript in general and React specifically, and is a preset option when generating an `eslintrc` file. [I also have one that I am using for a create-react-app project right now](https://github.com/solkaz/metroid-password-generator/blob/bitset/.eslintrc.js) that we can easily modify. I think it would be important, however, to have an agreed-upon style convention, and that conversation should probably be face-to-face (so after this weekend)

**Comment by Hopding** [comment]
I don't have much Javascript experience, so I don't know _which_ style or linter we would want to use. But, I certainly do think we should pick and use one.

**Comment by thebho** [comment]
Wow, that Airbnb one is popular.  That works for me.
