### ISSUE TITLE
Separating the current skill displayer into its own component

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#35]
Right now we're displaying the current skill's information with static elements (down at the bottom of the Skills.jsx file). We could make a separate component to decouple the current skill's interface from the general Skill component.

**Comment by thebho** [comment]
This makes sense.  @Hopding how does this effect what you are working on with the links story?

**Comment by Hopding** [comment]
This seems reasonable. It wouldn't have a major impact on #45. #45 is ready for merging (unless anybody requests changes), so I don't imagine we'll need to worry about merge conflicts in that respect.
