### ISSUE TITLE
Make an error component for bad urls

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/skilldirectoryui#41]
Right now, when a bad URL is entered, we render an absolutely hideous message. We should create a reusable component that we can plug in when the user navigates to a bad url. See <https://www.amazon.com/porcupine>.

**Comment by solkaz** [comment]
May I suggest that when a bad URL is entered, we redirect the user to a 404 page? It would decouple handling bad URLs from the page component, and instead hand that responsibility to react-router, which is its purpose anyways

**Comment by dane-johnson** [comment]
I don't think the user will appreciate the redirect. The beauty of a 404 is it doesn't break the user's mental model of the website. It just lets them know they looked in a bad place.

**Comment by Hopding** [comment]
I think we should also get our own herd of goats, and style our error pages like Amazon's, but with goats.
