### ISSUE TITLE
Discuss using a different request tool to access the API

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#46]
Axios is causing a lot of problems already.  Discuss other options.

Options:
https://github.com/request/request
https://facebook.github.io/react-native/docs/network.html
https://www.sitepoint.com/introduction-to-the-fetch-api/

**Comment by dane-johnson** [comment]
I've seen fetch used, but it also supports the Promise API.

**Comment by dane-johnson** [comment]
We could hard code our own using AJAX requests. Problem is that AJAX is designed to be asynchronous, which introduces a whole new set of problems with React

**Comment by Hopding** [comment]
I don't see why we cannot skip the wrapper and use [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) directly? I haven't actually done it before, but it doesn't look a lot different from axios' API.

**Comment by dane-johnson** [comment]
The main issue we are having with Axios is concurrency issues. Raw Promise is going to have these problems too, coupled with increased effort on our parts as it is a lot less refined.

**Comment by Hopding** [comment]
So we want a non-`Promise`-based tool?

**Comment by dane-johnson** [comment]
If we are going to get rid of Axios then I think we should.

**Comment by dane-johnson** [comment]
Given that the issues with Axios turned out to be our fault, I am going to close this issue.
