### ISSUE TITLE
Handling when a user clicks the 'x' (clear icon) in the Select component

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#49]
When a user clicks on the 'x' icon that to clear the text in the Select element, it passes `null` to `onChange` by way of `onSelectChange`, which will through an error, because it gets added to the API call string. Also, it does not actually clear the text in the Select field. It should be changed so that the normal behavior (i.e. the text is cleared) is implemented and it doesn't attempt to make a request

**Comment by thebho** [comment]
If there is a way to hide the `x` if nothing has been typed on the form this would be a good place to add that.

**Comment by thebho** [comment]
I think this has been fix, calling it done
