### ISSUE TITLE
Refactoring modal usage

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#54]
The way we use Modals currently is that every time we need to add a new modal in a component, we need to create a new `<Modal />` component that contains the actual modal element that's interacted with, and we also need to add a new state variable denoting its opened status, methods to close that specific modal, and bind those methods. Tedious

I propose that we instead have one `<Modal />` component which can display all types of modals we need. We should be able to pass in the modal to display using the children prop. We'd remove the open/close methods, and instead just set the component to display no modals.

**Comment by dane-johnson** [comment]
I think that this is a great idea, but I don't think [the creators of the component agree with you](https://github.com/reactjs/react-modal#examples). Maybe we ditch this dependency? `react-bootstrap` [already has a modal implementation](https://react-bootstrap.github.io/components.html#modals)

**Comment by solkaz** [comment]
I don't see how they disagree with me? It doesn't show how they handle having multiple types of modals in the first link you sent

**Comment by solkaz** [comment]
It might be nice to switch to react-bootstrap since we're already using it, but it should probably be discussed before we abandon it.

**Comment by thebho** [comment]
I'm gonna move this up as a "React Best Practices" story
