### ISSUE TITLE
Separating requests logic from SkillForm etc.

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#60]
`SkillForm.jsx` currently has logic to handle making a POST request to add a skill, as well as handling the error and closing the modal. I argue that that functionality should be brought back to the Skill component that instantiates it. If you look at the `Team` and `AddTeamMemberForm` components, I do the same thing, where `AddTeamMemberForm` simply gets the user input and passes it to the `Team` component when the submit button is clicked.

This should only take a few minutes, since it's been done before. One would just need to implement the pattern in `Skill` and `SkillForm`

**Comment by thebho** [comment]
Let's do it!
