### ISSUE TITLE
Routing Bug

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#71]
Latest build causing routing problems 

`Cannot GET /skills` for all endpoints

**Comment by thebho** [comment]
pushstate-server fails because of `Cannot find module 'eslint'` in the logs

**Comment by dane-johnson** [comment]
Try adding `npm install -g eslint` to the Dockerfile

**Comment by dane-johnson** [comment]
Or change `pushstate-server` to `node_modules/pushstate-server/bin/pushstate-server` in buildUI
