### ISSUE TITLE
Fix the sizing of add skill reviews

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#85]
Currently the text field is bigger than the modal so you have to scroll down to Save the review.

**Comment by thebho** [comment]
<img width="547" alt="screen shot 2017-01-19 at 3 15 13 pm" src="https://cloud.githubusercontent.com/assets/12362348/22125633/145bcf2c-de5a-11e6-801e-fd6c56b5e0bb.png">

**Comment by solkaz** [comment]
When does that happen to you? This is what the normal view is for me

<img width="849" alt="screen shot 2017-01-20 at 8 57 03 am" src="https://cloud.githubusercontent.com/assets/10211603/22153809/768ee00a-deee-11e6-9beb-f580a2f35feb.png">

**Comment by thebho** [comment]
The size of the box is appropriate, it's the negative space around the box that is the problem.  There is a buffer of between the overlay and content that is translucent and if you click there the modal closes.  That buffer should cover the whole parent, so I don't have access to the `Add Link` and other buttons while in an open modal

**Comment by thebho** [comment]
The way waffle handles it is a good example (except for the close modal functionality)

**Comment by thebho** [comment]
It happens in Chrome, and when I make the browser width smaller.  In Safari is looks correct
