### ISSUE TITLE
When adding a skill review with an apostrophe the review will not submit.

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#87]
```time="2017-01-19T22:18:57Z" level=warning msg="Handler Method: POST, gocql.errorFrame: line 1:332 missing EOF at 't' (INSERT INTO skillreviews JSON '{\"id\":\"458de82c-de95-11e6-92a3-0242ac120003\",\"skill_id\":\"e11eaf91-dceb-11e6-8b4e-0242ac120003\",\"team_member_id\":\"72ebf39b-dce0-11e6-8b4b-0242ac120003\",\"body\":\"Docker is great for managing process dependencies for developers.  I can run 4 different versions of Java in 4 different containers and I don'[t] have...)" ```

Need to add better description of error, too.

**Comment by solkaz** [comment]
Would this basically entail sanitizing the body section of a new skill review?

**Comment by dane-johnson** [comment]
I would think so. We might want to take a look at how the API layer handles this as well.
