### ISSUE TITLE
Using one select component

### ISSUE THREAD

**Issue by solkaz** [maryvilledev/skilldirectoryui#99]
We are using two different `select` components, one from [react-select](https://github.com/JedWatson/react-select), which is used in `Skills` and `Team`; we also use react-bootstrap's select in `AddSkillForm`. It seems to me that it would make more sense to use one or the other, unless we have a reason to include both of them.

**Comment by dane-johnson** [comment]
I vote for the vanilla bootstrap component. It has a lot less overhead, and we could remove a dependency from the project.
